ALTER TABLE "cases"
ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;

ALTER TABLE "cases"
ADD COLUMN IF NOT EXISTS "volatilityScore" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "cases"
ADD COLUMN IF NOT EXISTS "volatilityLabel" TEXT NOT NULL DEFAULT 'LOW';
