ALTER TABLE "battles"
  ADD COLUMN IF NOT EXISTS "modeBorrow" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "battle_slots"
  ADD COLUMN IF NOT EXISTS "borrowPercent" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "battle_slots"
  ADD COLUMN IF NOT EXISTS "paidAmountAtomic" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "battle_slots"
  ADD COLUMN IF NOT EXISTS "payoutAtomic" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "battle_slots"
  ADD COLUMN IF NOT EXISTS "winWeightAtomic" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "battle_slots"
  ADD COLUMN IF NOT EXISTS "profitAtomic" BIGINT NOT NULL DEFAULT 0;
